### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by Bellagirl-maker** [yusufobr/todo-list-review#2]
@yusufobr Great job on completing this project. 👍 
 However there are some changes that needs to be implemented in order to follow JavaScript best practices. Kindly use arrow functions instead of normal functions in your interactive.js file because this makes your codebase DRY and KISS for best JavaScript practices.

**Comment by yusufobr** [comment]
Hi @Bellagirl-maker , Your required changes are taken into consideration, thank you
